### ISSUE TITLE
The demo doesn't load any more

### ISSUE THREAD

**Issue by NigelThorne** [jlengrand/elm-firebase#8]
There is an error on your demo site. The login button fails with "the hosted domain can't run that feature" or something. 
You need to add your hosted domain to some permissions in Firebase.

**Comment by jlengrand** [comment]
Ha, alright. I know where that comes from, Nelify autoported all the apps from the .com to the .app domain. 

I haven't touched the demo in a while. Thanks for notifying!

**Comment by jlengrand** [comment]
Confirming, adding the .app works as expected. Thanks!
