### ISSUE TITLE
Cloning and running npm start does nothing

### ISSUE THREAD

**Issue by NigelThorne** [jlengrand/elm-firebase#9]
I clone the repo. 
run npm install 
wait
create an .env file 
run npm start
... nothing happens. 
no error. no "hosting localhost:xxx" ... nothing :(

I'm running elm 0.19.1

**Comment by NigelThorne** [comment]
I just needed to > npm install create-elm-app@latest --global

**Comment by jlengrand** [comment]
It's strange though, the create-elm-app package shouldn't be needed globally as it's part of the dev dependencies. https://github.com/jlengrand/elm-firebase/blob/master/package.json#L14

**Comment by jlengrand** [comment]
Can confirm, I just cloned from scratch again and I have no problem running the app using `$ npm install` (using npm 6.14)

**Comment by NigelThorne** [comment]
Do you have a global elm-app command on your path?

**Comment by jlengrand** [comment]
Alright, just to be sure I wiped out all trace of `create-elm-app` from my system and ran from scratch again 👍 

```
➜  elm-firebase git:(master) elm-app
zsh: command not found: elm-app
➜  elm-firebase git:(master) create-elm-app
zsh: command not found: create-elm-app
➜  elm-firebase git:(master) npm install
audited 1439 packages in 6.565s

35 packages are looking for funding
  run `npm fund` for details

found 15 vulnerabilities (12 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
➜  elm-firebase git:(master) npm start

> elm-firebase@1.0.0 start /Users/jlengrand/IdeaProjects/elm-firebase
> elm-app start

^C
➜  elm-firebase git:(master)
```

I CTRL + C at this point, because the elm-app dev server grabs the terminal but everything runs as expected. 

The fact that `create-elm-app` is in the devDependencies should mean that it's present in your `.node_modules/.bin` :

```
➜  elm-firebase git:(master) ll node_modules/.bin
...
lrwxr-xr-x  1 jlengrand  staff    36B Sep 11 15:33 elm-app -> ../create-elm-app/bin/elm-app-cli.js
...
```

Can you confirm this? If you do `npm start`, npm should have access to the .bin folder and have it as part of its path, making it unnecessary globally.

**Comment by jlengrand** [comment]
I'll reopen in the meantime :)

**Comment by joshuanianji** [comment]
I had the same issue, and I found [this article](https://medium.com/@rick38yip/npm-scripts-not-working-7e7dfbc92956) that fixed it for me. I basically had to run `npm config set ignore-scripts false`.

**Comment by jlengrand** [comment]
I read the article as well and I guess I could do that. I don't quite like doing something without understanding what the problem behind it is though. Let me investigate a bit mroe

**Comment by jlengrand** [comment]
Yeah I just ran again from a clean system without anything installed before and cannot reproduce. I wonder if the issue does not come from #11 , which is fixed now.

I'll close, but if you have more information I'm happy to reopen and look deeper.
